import re
from fastapi import FastAPI
from pydantic import BaseModel

from app.services.hindsight import recall_memories, retain_memory
from app.services.decision import make_decision
from app.services.groq import generate_decision
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="Precedent API",
    description="AI-powered chargeback intelligence agent",
    version="0.1.0",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChargebackCase(BaseModel):
    case_id: str
    dispute_type: str
    amount: float
    customer_claim: str
    merchant_evidence: str
class ChargebackOutcome(BaseModel):
    case_id: str
    outcome: str
    actual_result: str
    lesson: str

@app.get("/")
def root():
    return {
        "message": "Precedent API is running"
    }


@app.get("/health")
def health():
    return {
        "status": "healthy"
    }


@app.post("/analyze")
def analyze_case(case: ChargebackCase):

    query = f"""
    Chargeback dispute:
    Type: {case.dispute_type}
    Customer claim: {case.customer_claim}
    Merchant evidence: {case.merchant_evidence}

    Find relevant previous chargeback experiences,
    outcomes, evidence strategies, and lessons.
    """

    memories = recall_memories(query)
    try:
        ai_decision = generate_decision(case, memories)
        fallback_used = False
    except Exception as e:
        fallback_used = True
        heuristic = make_decision(case, memories)
        ai_decision = {
            "recommendation": heuristic.get("recommendation", "REVIEW"),
            "confidence": 60 if heuristic.get("recommendation") == "FIGHT" else 40,
            "evidence_to_submit": heuristic.get("evidence_strategy", []),
            "reasoning": (
                f"Generated by local rule-based fallback (upstream AI service unavailable: {str(e)}). "
                f"{heuristic.get('reason', '')}"
            ),
            "memory_used": False,
        }

    recalled_list = (
        [memory.text for memory in memories.results]
        if hasattr(memories, "results") and memories.results
        else []
    )

    if fallback_used:
        memory_used = False
    else:
        raw_mem_used = ai_decision.get("memory_used")
        if isinstance(raw_mem_used, bool):
            memory_used = raw_mem_used
        elif isinstance(raw_mem_used, str):
            memory_used = (
                len(raw_mem_used.strip()) > 0
                and raw_mem_used.strip().lower() not in ("false", "none", "no", "0", "n/a")
            )
        else:
            memory_used = len(recalled_list) > 0

    previous_outcome = None
    if recalled_list:
        first_mem = recalled_list[0]
        match = re.search(r"Outcome:\s*(WON|LOST|FOLDED|PENDING)", first_mem, re.IGNORECASE)
        if match:
            previous_outcome = match.group(1).upper()
        else:
            previous_outcome = first_mem

    decision_payload = {
        "recommendation": str(ai_decision.get("recommendation", "FIGHT")),
        "confidence": ai_decision.get("confidence", 70),
        "reasoning": str(ai_decision.get("reasoning", "")),
        "evidence_to_submit": ai_decision.get("evidence_to_submit", []),
    }

    return {
        "case_id": case.case_id,
        "dispute_type": case.dispute_type,
        "amount": case.amount,
        "decision": decision_payload,
        # Preserve top-level fields for direct access and backward compatibility
        "recommendation": decision_payload["recommendation"],
        "confidence": decision_payload["confidence"],
        "reasoning": decision_payload["reasoning"],
        "evidence_to_submit": decision_payload["evidence_to_submit"],
        "memory_used": memory_used,
        "recalled_memories": recalled_list,
        "previous_outcome": previous_outcome,
        "memories": [
            {
                "type": memory.type,
                "text": memory.text,
            }
            for memory in memories.results
        ]
        if hasattr(memories, "results") and memories.results
        else [],
    }
@app.post("/outcome")
def record_outcome(outcome: ChargebackOutcome):

    memory = f"""
    Precedent chargeback outcome:

    Case ID: {outcome.case_id}
    Outcome: {outcome.outcome}
    Actual result: {outcome.actual_result}
    Lesson learned: {outcome.lesson}

    This outcome should be used as precedent for future similar
    chargeback decisions.
    """

    result = retain_memory(memory)

    return {
        "status": "stored",
        "case_id": outcome.case_id,
        "message": "Outcome stored in Hindsight.",
    }