import os
import re
from typing import Optional
from contextlib import asynccontextmanager

from fastapi import FastAPI, Header, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import stripe

from app.services.decision import make_decision
from app.services.event_store import init_db, list_webhook_events
from app.services.groq import generate_decision
from app.services.hindsight import recall_memories, retain_memory
from app.services.stripe_service import (
    create_payment_intent,
    get_stripe_dispute,
    get_stripe_publishable_key,
    get_stripe_secret_key,
    get_stripe_status,
    get_stripe_webhook_secret,
    list_stripe_disputes,
    list_stripe_payments,
    process_webhook_event_payload,
    retrieve_payment_intent,
)


@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    yield


app = FastAPI(
    title="Precedent API",
    description="AI-powered chargeback intelligence agent",
    version="0.1.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChargebackCase(BaseModel):
    case_id: str
    dispute_type: str
    amount: float
    customer_claim: str
    merchant_evidence: str


class ChargebackOutcome(BaseModel):
    case_id: str
    outcome: str
    actual_result: str
    lesson: str


class CreatePaymentIntentRequest(BaseModel):
    amount_cents: int
    currency: str = "usd"
    customer_name: Optional[str] = None
    customer_email: Optional[str] = None
    description: Optional[str] = None
    metadata: Optional[dict] = None
    payment_method_type: Optional[str] = None


@app.get("/")
def root():
    return {
        "message": "Precedent API is running"
    }


@app.get("/health")
def health():
    return {
        "status": "healthy"
    }


@app.post("/analyze")
def analyze_case(case: ChargebackCase):
    query = f"""
    Chargeback dispute:
    Type: {case.dispute_type}
    Customer claim: {case.customer_claim}
    Merchant evidence: {case.merchant_evidence}

    Find relevant previous chargeback experiences,
    outcomes, evidence strategies, and lessons.
    """

    memories = recall_memories(query)
    try:
        ai_decision = generate_decision(case, memories)
        fallback_used = False
    except Exception as e:
        fallback_used = True
        heuristic = make_decision(case, memories)
        ai_decision = {
            "recommendation": heuristic.get("recommendation", "REVIEW"),
            "confidence": 60 if heuristic.get("recommendation") == "FIGHT" else 40,
            "evidence_to_submit": heuristic.get("evidence_strategy", []),
            "reasoning": (
                f"Generated by local rule-based fallback (upstream AI service unavailable: {str(e)}). "
                f"{heuristic.get('reason', '')}"
            ),
            "memory_used": False,
        }

    recalled_list = (
        [memory.text for memory in memories.results]
        if hasattr(memories, "results") and memories.results
        else []
    )

    if fallback_used:
        memory_used = False
    else:
        raw_mem_used = ai_decision.get("memory_used")
        if isinstance(raw_mem_used, bool):
            memory_used = raw_mem_used
        elif isinstance(raw_mem_used, str):
            memory_used = (
                len(raw_mem_used.strip()) > 0
                and raw_mem_used.strip().lower() not in ("false", "none", "no", "0", "n/a")
            )
        else:
            memory_used = len(recalled_list) > 0

    previous_outcome = None
    if recalled_list:
        first_mem = recalled_list[0]
        match = re.search(r"Outcome:\s*(WON|LOST|FOLDED|PENDING)", first_mem, re.IGNORECASE)
        if match:
            previous_outcome = match.group(1).upper()
        else:
            previous_outcome = first_mem

    decision_payload = {
        "recommendation": str(ai_decision.get("recommendation", "FIGHT")),
        "confidence": ai_decision.get("confidence", 70),
        "reasoning": str(ai_decision.get("reasoning", "")),
        "evidence_to_submit": ai_decision.get("evidence_to_submit", []),
    }

    return {
        "case_id": case.case_id,
        "dispute_type": case.dispute_type,
        "amount": case.amount,
        "decision": decision_payload,
        "recommendation": decision_payload["recommendation"],
        "confidence": decision_payload["confidence"],
        "reasoning": decision_payload["reasoning"],
        "evidence_to_submit": decision_payload["evidence_to_submit"],
        "memory_used": memory_used,
        "recalled_memories": recalled_list,
        "previous_outcome": previous_outcome,
        "memories": [
            {
                "type": getattr(memory, "type", "precedent"),
                "text": getattr(memory, "text", str(memory)),
            }
            for memory in getattr(memories, "results", [])
        ],
    }


@app.post("/outcome")
def record_outcome(outcome: ChargebackOutcome):
    memory = f"""
    Precedent chargeback outcome:

    Case ID: {outcome.case_id}
    Outcome: {outcome.outcome}
    Actual result: {outcome.actual_result}
    Lesson learned: {outcome.lesson}

    This outcome should be used as precedent for future similar
    chargeback decisions.
    """

    retain_memory(memory)

    return {
        "status": "stored",
        "case_id": outcome.case_id,
        "message": "Outcome stored in Hindsight.",
    }


# ============================================================================
# Stripe Webhook & Test-Mode Integration
# ============================================================================

async def handle_stripe_webhook_request(
    request: Request,
    stripe_signature: Optional[str],
):
    webhook_secret = get_stripe_webhook_secret()
    if not webhook_secret:
        raise HTTPException(
            status_code=500,
            detail="STRIPE_WEBHOOK_SECRET is not configured on the server",
        )

    if not stripe_signature:
        raise HTTPException(
            status_code=400,
            detail="Missing Stripe-Signature header",
        )

    raw_body = await request.body()

    try:
        event = stripe.Webhook.construct_event(
            payload=raw_body,
            sig_header=stripe_signature,
            secret=webhook_secret,
        )
    except stripe.SignatureVerificationError as e:
        raise HTTPException(
            status_code=400,
            detail=f"Webhook signature verification failed: {str(e)}",
        )
    except Exception as e:
        raise HTTPException(
            status_code=400,
            detail=f"Failed to parse webhook payload: {str(e)}",
        )

    result = process_webhook_event_payload(event)
    return result


@app.post("/webhook/stripe")
async def stripe_webhook_endpoint(
    request: Request,
    stripe_signature: Optional[str] = Header(None, alias="Stripe-Signature"),
):
    return await handle_stripe_webhook_request(request, stripe_signature)


@app.post("/stripe/webhook")
async def stripe_webhook_alias_endpoint(
    request: Request,
    stripe_signature: Optional[str] = Header(None, alias="Stripe-Signature"),
):
    return await handle_stripe_webhook_request(request, stripe_signature)


@app.get("/stripe/status")
def stripe_status():
    return get_stripe_status()


@app.get("/stripe/payments")
def stripe_payments(limit: int = 20):
    if not get_stripe_secret_key():
        raise HTTPException(
            status_code=503,
            detail="STRIPE_SECRET_KEY is not configured",
        )
    try:
        payments = list_stripe_payments(limit=limit)
        return {
            "payments": payments,
            "total": len(payments),
        }
    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"Error retrieving Stripe payments: {str(e)}",
        )


@app.get("/stripe/disputes")
def stripe_disputes(limit: int = 20):
    if not get_stripe_secret_key():
        raise HTTPException(
            status_code=503,
            detail="STRIPE_SECRET_KEY is not configured",
        )
    try:
        disputes = list_stripe_disputes(limit=limit)
        return {
            "disputes": disputes,
            "total": len(disputes),
        }
    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"Error retrieving Stripe disputes: {str(e)}",
        )


@app.get("/stripe/disputes/{dispute_id}")
def stripe_dispute_detail(dispute_id: str):
    if not get_stripe_secret_key():
        raise HTTPException(
            status_code=503,
            detail="STRIPE_SECRET_KEY is not configured",
        )
    try:
        return get_stripe_dispute(dispute_id)
    except KeyError:
        raise HTTPException(
            status_code=404,
            detail=f"Dispute {dispute_id} not found",
        )
    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"Error retrieving dispute from Stripe: {str(e)}",
        )


@app.get("/stripe/webhooks")
def stripe_webhooks_history(limit: int = 50):
    return {
        "webhooks": list_webhook_events(limit=limit),
    }


@app.get("/stripe/config")
def stripe_config():
    key = get_stripe_secret_key()
    return {
        "publishable_key": get_stripe_publishable_key(),
        "mode": "test" if key.startswith("sk_test_") else "live" if key.startswith("sk_live_") else "unconfigured",
        "google_pay_supported": True,
        "connected": bool(key),
    }


@app.post("/stripe/create-payment-intent")
def stripe_create_payment_intent(req: CreatePaymentIntentRequest):
    if not get_stripe_secret_key():
        raise HTTPException(
            status_code=503,
            detail="STRIPE_SECRET_KEY is not configured",
        )
    try:
        return create_payment_intent(
            amount_cents=req.amount_cents,
            currency=req.currency,
            customer_name=req.customer_name,
            customer_email=req.customer_email,
            description=req.description,
            metadata=req.metadata,
            payment_method_type=req.payment_method_type,
        )
    except ValueError as ve:
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Failed to create PaymentIntent: {str(e)}")


@app.get("/stripe/payment-intent/{payment_intent_id}")
def stripe_get_payment_intent(payment_intent_id: str):
    if not get_stripe_secret_key():
        raise HTTPException(
            status_code=503,
            detail="STRIPE_SECRET_KEY is not configured",
        )
    try:
        return retrieve_payment_intent(payment_intent_id)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"PaymentIntent {payment_intent_id} not found")
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Failed to retrieve PaymentIntent: {str(e)}")


# API Prefix aliases for consistent frontend proxy routing
@app.get("/api/stripe/status")
def api_stripe_status():
    return stripe_status()


@app.get("/api/stripe/config")
def api_stripe_config():
    return stripe_config()


@app.post("/api/stripe/create-payment-intent")
def api_stripe_create_payment_intent(req: CreatePaymentIntentRequest):
    return stripe_create_payment_intent(req)


@app.get("/api/stripe/payment-intent/{payment_intent_id}")
def api_stripe_get_payment_intent(payment_intent_id: str):
    return stripe_get_payment_intent(payment_intent_id)


@app.get("/api/stripe/payments")
def api_stripe_payments(limit: int = 20):
    return stripe_payments(limit=limit)


@app.get("/api/stripe/disputes")
def api_stripe_disputes(limit: int = 20):
    return stripe_disputes(limit=limit)


@app.get("/api/stripe/disputes/{dispute_id}")
def api_stripe_dispute_detail(dispute_id: str):
    return stripe_dispute_detail(dispute_id)

